# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083ef7d9f2e204489c0336a8cc181ae3eb1e52d1cdcd20f17e0ae3905e376980b63a94b45cdc7babd25d438fe3563f90a2971fd7899d7055efaa5ddada9ec070

test:
  secret_key_base: e319ed261d46540114500fcf1a1de177b1533ebaa3e2d64ebb33e1f6ae84c555c7aadc321b21d5591c06099178d5cafbcacb27448f2a1f14e21126add16f7d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
